site_name: Nirant Kasliwal
site_url: https://nirantk.com/
site_author: Nirant Kasliwal

remote_branch: gh-pages
remote_name: origin

docs_dir: docs

plugins:
  - search
  - social
  - blog:
      enabled: !ENV CI
      blog_dir: docs/writing
      blog_toc: true
      post_dir: docs/writing/
      post_url_format: "{slug}"

theme:
  name: material
  # logo: assets/logo/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  accent:
    # Primary color
    color: "#3f51b5"
    # Text color for primary color
    text: "#ffffff"

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  # - highlight
  - def_list
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_bases: false
            show_if_no_docstring: true
            merge_init_into_class: true
            show_root_toc_entry: false
            show_inheritance: true
            show_private: false
            show_special_members: false
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false
      tag_remove_configs:
        remove_cell_tags:
          - Remove_cell
        remove_all_outputs_tags:
          - Remove_all_output
        remove_single_output_tags:
          - Remove_single_output
        remove_input_tags:
          - Remove_input

extra:
  # analytics:
  #   provider: google
  #   property: G-686PKP2V2V
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nirantk
    - icon: fontawesome/brands/github
      link: https://github.com/nirantk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nirant/

# extra_css:
#   - stylesheets/extra.css
extra_javascript:
  # - javascripts/mathjax.js
  # - javascripts/analytics.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2024 Nirant Kasliwal

