[[main]]
  name = "Summaries"
  url = "/docs/resources/"
  weight = 60
  identifier = "summaries"
  parent = "ai"

[[main]]
  name = "DeepHack Demos"
  url = "/deephackdemos/"
  weight = 60
  identifier = "deephack"
  parent = "ai"

[[main]]
  name = "Generative AI Community"
  url = "/ai"
  weight = 10
  identifier = "ai"

[[main]]
  name = "Demo Day October 2023"
  url = "/demoday102023/"
  weight = 30
  identifier = "demoday102023"
  parent = "ai"

[[main]]
  name = "Community Guidelines"
  url = "/community"
  weight = 20
  identifier = "community"
  parent = "ai"

[[main]]
  name = "Writing"
  url = "/writing/"
  weight = 20

[[main]]
  name = "Work With Me"
  url = "/work-with-me/"
  weight = 30
  identifier = "work-with-me"

[[main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about"
  parent = "work-with-me"

[[main]]
  name = "Introduction"
  weight = 30
  identifier = "introduction"
  url = "/introduction"
  parent = "work-with-me"

[[main]]
  name = "Endorsed Friends"
  weight = 40
  identifier = "endorsed"
  url = "/endorsed"
  parent = "work-with-me"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/NirantK"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/NirantK"
  weight = 20

[[social]]
  name = "Linkedin"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-linkedin\"><path d=\"M12 9.55C12.917 8.613 14.111 8 15.5 8a5.5 5.5 0 0 1 5.5 5.5V21h-2v-7.5a3.5 3.5 0 0 0-7 0V21h-2V8.5h2v1.05zM5 6.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm-1 2h2V21H4V8.5z\"></path></svg>"
  url = "https://linkedin.com/in/nirant"
  weight = 20