authors:
  nirant:
    name: Nirant Kasliwal
    description: AI Engineer
    avatar: https://pbs.twimg.com/profile_images/1716473928590512128/F7cyV0D1_400x400.jpg
  kumarshivendu:
    name: Kumar Shivendu
    description: Tech @ Qdrant
    avatar: https://www.kshivendu.dev/_next/image?url=%2Fstatic%2Fimages%2Fshivendu.jpg
  shyam-sankar:
    name: Shyam Sankar
    description: CTO @ Palantir
    avatar: https://www.linkedin.com/in/shyamsankar/
