# Deploy your Hyas site to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch submodules like themes

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the site
      run: hugo --minify

    - name: Show Current Directory
      run: pwd

    - name: List Files in Current Directory
      run: ls -la

    - name: List Files in 'public' Directory
      run: ls -la public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages